# Generated by Django 4.2.1 on 2023-08-05 00:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account_api", "0002_alter_account_password"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="account",
            options={},
        ),
        migrations.RemoveField(
            model_name="account",
            name="date_joined",
        ),
        migrations.RemoveField(
            model_name="account",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="account",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="account",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="account",
            name="is_staff",
        ),
        migrations.RemoveField(
            model_name="account",
            name="is_superuser",
        ),
        migrations.RemoveField(
            model_name="account",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="account",
            name="user_permissions",
        ),
    ]
