# Generated by Django 4.2.1 on 2023-08-05 00:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "account_api",
            "0003_alter_account_options_remove_account_date_joined_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
