# Generated by Django 4.2.1 on 2023-05-04 20:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("world_api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="country",
            old_name="campaign",
            new_name="world",
        ),
    ]
