# Generated by Django 4.2.1 on 2023-05-05 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("world_api", "0002_rename_campaign_country_world"),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "system",
                    models.CharField(
                        choices=[("5E", "DnD 5E"), ("pf2E", "Pathfinder 2E")],
                        default="pf2E",
                        max_length=4,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "picture",
                    models.URLField(
                        blank=True,
                        default="https://placehold.co/600x400",
                        max_length=300,
                    ),
                ),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.RenameField(
            model_name="world",
            old_name="picture_url",
            new_name="picture",
        ),
        migrations.AlterField(
            model_name="city",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cities",
                to="world_api.country",
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="country",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="country",
            name="world",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="country",
                to="world_api.world",
            ),
        ),
        migrations.AlterField(
            model_name="world",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name="NpcVO",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "picture",
                    models.URLField(
                        blank=True,
                        default="https://placehold.co/400x400",
                        max_length=300,
                    ),
                ),
                ("chr_class", models.CharField(max_length=20)),
                ("description", models.TextField(blank=True)),
                (
                    "current_city",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="npcs",
                        to="world_api.city",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="world",
            name="campaign",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="world",
                to="world_api.campaign",
            ),
        ),
    ]
