# Generated by Django 4.2.1 on 2023-05-05 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("world_api", "0003_campaign_rename_picture_url_world_picture_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="npcvo",
            name="visited_cities",
            field=models.ManyToManyField(
                blank=True, related_name="npc_visited", to="world_api.city"
            ),
        ),
        migrations.AlterField(
            model_name="npcvo",
            name="current_city",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="npc_current",
                to="world_api.city",
            ),
        ),
    ]
