# Generated by Django 4.2.1 on 2023-05-05 03:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("world_api", "0004_npcvo_visited_cities_alter_npcvo_current_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="npcvo",
            name="chr_class",
            field=models.CharField(default="Civilian", max_length=20),
        ),
    ]
