# Generated by Django 4.2.1 on 2023-05-06 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("world_api", "0005_alter_npcvo_chr_class"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="npcvo",
            name="chr_class",
        ),
        migrations.RemoveField(
            model_name="npcvo",
            name="description",
        ),
        migrations.RemoveField(
            model_name="npcvo",
            name="picture",
        ),
        migrations.AddField(
            model_name="npcvo",
            name="vip",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="country",
            name="world",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="countries",
                to="world_api.world",
            ),
        ),
    ]
