# Generated by Django 4.2.1 on 2023-05-06 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("world_api", "0006_remove_npcvo_chr_class_remove_npcvo_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="npcvo",
            name="visited_cities",
        ),
        migrations.RemoveField(
            model_name="world",
            name="campaign",
        ),
        migrations.AlterField(
            model_name="npcvo",
            name="current_city",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="npcs",
                to="world_api.city",
            ),
        ),
        migrations.DeleteModel(
            name="Campaign",
        ),
    ]
