# Generated by Django 4.2.1 on 2023-05-24 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "world_api",
            "0007_remove_npcvo_visited_cities_remove_world_campaign_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cities",
                to="world_api.country",
            ),
        ),
        migrations.AlterField(
            model_name="country",
            name="world",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="countries",
                to="world_api.world",
            ),
        ),
        migrations.AlterField(
            model_name="npcvo",
            name="current_city",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="npcs",
                to="world_api.city",
            ),
        ),
    ]
