# Generated by Django 4.2.1 on 2023-06-30 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("world_api", "0008_alter_city_country_alter_country_world_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "picture",
                    models.URLField(
                        blank=True,
                        default="https://placehold.co/600x400",
                        max_length=300,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="districts",
                        to="world_api.city",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="NpcVO",
        ),
    ]
